# Flyway configuration file

# JDBC URL to connect to the database
flyway.url=jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}

# User to connect to the database
flyway.user=${POSTGRES_USER}

# Password to connect to the database
flyway.password=${POSTGRES_PASSWORD}

# Location of the SQL migrations
flyway.locations=filesystem:sql_migrations